# Generated by Django 4.0.4 on 2022-09-21 06:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkInfo',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('company_name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('1', 'information system/software'), ('2', 'finance'), ('3', 'hotel'), ('4', 'hospital')], max_length=50)),
                ('board', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('job_title', models.CharField(max_length=150)),
                ('level', models.CharField(choices=[('SA', 'senior architect'), ('SL', 'senior level'), ('ML', 'mid level'), ('A', 'associate'), ('J', 'junior'), ('I', 'intern')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('responsiblity', models.TextField()),
                ('is_current', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'WorkInfo',
                'verbose_name_plural': 'WorksInfo',
                'db_table': 'work_info',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('mobile', models.CharField(max_length=20)),
                ('temporary_address', models.CharField(max_length=150)),
                ('permanent_address', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'others')], max_length=10)),
                ('dob', models.DateField()),
                ('marital_status', models.BooleanField(default=False)),
                ('religion', models.CharField(choices=[('H', 'hinduism'), ('I', 'isalm'), ('C', 'christianity')], max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'PersonalInfo',
                'verbose_name_plural': 'PersonalInfo',
                'db_table': 'personal_info',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='LanguageInfo',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('language', models.CharField(choices=[('1', 'english'), ('2', 'nepali'), ('3', 'french'), ('4', 'japanese')], max_length=50)),
                ('speaking', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('reading', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('writing', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('listening', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'LanguageInfo',
                'verbose_name_plural': 'LanguagesInfo',
                'db_table': 'language_info',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('job_categories', models.CharField(max_length=250)),
                ('position', models.CharField(choices=[('SA', 'senior architect'), ('SL', 'senior level'), ('ML', 'mid level'), ('A', 'associate'), ('J', 'junior'), ('I', 'intern')], max_length=20)),
                ('available_for', models.CharField(max_length=30)),
                ('specializations', models.CharField(blank=True, max_length=250, null=True)),
                ('skills', models.TextField()),
                ('expected_salary', models.PositiveIntegerField()),
                ('current_salary', models.PositiveIntegerField()),
                ('carrer_summery', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'JobInfo',
                'verbose_name_plural': 'JobsInfo',
                'db_table': 'job_info',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='EducationInfo',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('degree', models.CharField(max_length=150)),
                ('program', models.CharField(max_length=150)),
                ('board', models.CharField(max_length=150)),
                ('institiue_name', models.CharField(max_length=150)),
                ('currently_studying', models.BooleanField(default=False)),
                ('marks', models.CharField(max_length=20)),
                ('graduation_year', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'EducationInfo',
                'verbose_name_plural': 'EducationsInfo',
                'db_table': 'education_info',
                'ordering': ['created_on'],
            },
        ),
    ]
